version: '3'

services:
  go_server:
    container_name: go_server
    build: ./server
    ports: 
      - 8888:8888
    volumes:
      - ./server:/api

  mock_mysql:
    env_file: ./docker/db/.env
    image: mysql:5.7
    container_name: mock_mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_RPASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      TZ: ${DB_TZ}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes: 
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports: 
      - ${DB_PORT}:3306